project_id = "rzsailqcijraplggryyy"

[functions.generate-agent-code]
verify_jwt = true

[functions.get-agent-profile]
verify_jwt = false

[functions.send-response-email]
verify_jwt = true

[functions.aura-generate-response]
verify_jwt = true
