import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'es' | 'en' | 'fr' | 'de' | 'pt' | 'zh';

export interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.properties': 'Propiedades',
    'nav.agents': 'Nuestros Agentes',
    'nav.clients': 'Nuestros Clientes',
    'nav.about': 'Sobre Nosotros',
    'nav.contact': 'Contacto',
    'nav.login': 'Iniciar Sesión',
    'nav.register': 'Registrarse',
    'nav.dashboard': 'Panel',
    'nav.signOut': 'Cerrar Sesión',
    
    // Hero Section
    'hero.title': 'Hogar para tu Familia, Proyectos para tu Futuro',
    'hero.subtitle': 'La red de franquicias inmobiliarias más grande de Bolivia. Miles de propiedades verificadas, agentes certificados y el respaldo de DOMINIO.',
    'hero.sellRent': 'Vende o Alquila',
    'hero.explore': 'Explorar Propiedades',
    'hero.franchise': 'Únete como Franquicia',
    
    // Property Types
    'properties.featured': 'Propiedades Destacadas',
    'properties.success': 'Éxitos Recientes',
    'properties.house': 'Casas',
    'properties.apartment': 'Departamentos',
    'properties.land': 'Terrenos',
    'properties.office': 'Oficinas',
    'properties.commercial': 'Local comercial',
    
    // Stats
    'stats.title': 'Números que Hablan por Sí Solos',
    'stats.properties': 'Propiedades Activas',
    'stats.franchises': 'Franquicias Activas',
    'stats.cities': 'Ciudades',
    'stats.sales': 'Ventas Mensuales',
    
    // Language Selector
    'language.select': 'Seleccionar idioma',
    'language.spanish': 'Español',
    'language.english': 'English',
    'language.french': 'Français',
    'language.german': 'Alemán',
    'language.portuguese': 'Portugués (Brasil)',
    'language.chinese': 'Chino (tradicional)',

    // Properties page
    'properties.title': 'Busca tu próximo hogar',
    'properties.subtitle': 'Filtra por ciudad, presupuesto, habitaciones y más. Todas las propiedades están verificadas por DOMINIO.',
    'properties.filters': 'Filtros',
    'properties.transactionType': 'Tipo de Transacción',
    'properties.all': 'Todas',
    'properties.sale': 'Venta',
    'properties.rent': 'Alquiler',
    'properties.anticretico': 'Anticrético',
    'properties.department': 'Departamento',
    'properties.allDepartments': 'Todos los departamentos',
    'properties.selectDepartment': 'Selecciona departamento',
    'properties.province': 'Provincia',
    'properties.allProvinces': 'Todas las provincias',
    'properties.selectProvince': 'Selecciona provincia',
    'properties.specificZone': 'Zona específica',
    'properties.allZones': 'Todas las zonas',
    'properties.minPrice': 'Precio mín.',
    'properties.maxPrice': 'Precio máx.',
    'properties.bedrooms': 'Habitaciones',
    'properties.bathrooms': 'Baños',
    'properties.propertyType': 'Tipo',
    'properties.select': 'Selecciona',
    'properties.lifestyle': 'Búsqueda AURA (estilo de vida)',
    'properties.lifestylePlaceholder': 'Ej. cerca de parques, zona tranquila, coworking...',
    'properties.searchNearMe': 'Buscar cerca de mí',
    'properties.amenities': 'Amenidades',
    'properties.search': 'Buscar',
    'properties.clearFilters': 'Limpiar filtros',
    'properties.results': 'Resultados',
    'properties.propertiesFound': 'propiedades',
    'properties.loading': 'Cargando propiedades...',
    'properties.noResults': 'No se encontraron propiedades con los filtros seleccionados.',
    'properties.tryDifferentFilters': 'Intenta con filtros diferentes.',

    // Agents page
    'agents.title': 'Nuestros Agentes',
    'agents.subtitle': 'Profesionales certificados y experimentados, listos para ayudarte a encontrar la propiedad perfecta en toda Bolivia.',
    'agents.searchPlaceholder': 'Buscar por nombre o código de agente...',
    'agents.minRating': 'Calificación mínima',
    'agents.allRatings': 'Todas las calificaciones',
    'agents.stars': 'estrellas',
    'agents.showing': 'Mostrando',
    'agents.of': 'de',
    'agents.agentsText': 'agentes',
    'agents.soonTitle': 'Próximamente',
    'agents.soonSubtitle': 'Estamos preparando el perfil de nuestros agentes profesionales.',
    'agents.realEstateAgent': 'Corredor de Bienes Raíces',
    'agents.code': 'Código',
    'agents.availableInBolivia': 'Disponible en Bolivia',
    'agents.viewFullProfile': 'Ver Perfil Completo',
    'agents.loadMore': 'Cargar más agentes',
    'agents.needHelp': '¿Necesitas ayuda personalizada?',
    'agents.helpText': 'Nuestros agentes están listos para asesorarte en la búsqueda de tu propiedad ideal. Contacta directamente con cualquiera de ellos.',
    'agents.contactNow': 'Contactar Ahora',
    'agents.loading': 'Cargando agentes...',

    // About page
    'about.title': 'Sobre DOMINIO',
    'about.defaultContent': 'DOMINIO Inmobiliaria nació de la visión de crear la red de franquicias inmobiliarias más grande y confiable de Bolivia. Nuestra misión es conectar personas con hogares, brindando transparencia, confianza y excelencia en cada transacción.',
    'about.pillarsTitle': 'Nuestros Pilares',
    'about.pillarsSubtitle': 'Los valores y principios que guían nuestro trabajo diario y nos impulsan hacia la excelencia.',
    'about.mission': 'Nuestra Misión',
    'about.missionContent': 'Ser el puente confiable entre las personas y sus sueños inmobiliarios, proporcionando servicios de excelencia y transparencia en cada transacción.',
    'about.vision': 'Nuestra Visión',
    'about.visionContent': 'Convertirnos en la red inmobiliaria líder en Bolivia, reconocida por nuestra integridad, innovación y compromiso con nuestros clientes.',
    'about.values': 'Nuestros Valores',
    'about.valuesContent': 'Transparencia, Confianza, Excelencia, Innovación y Compromiso con nuestros clientes y comunidades.',
    'about.objectives': 'Nuestros Objetivos',
    'about.objectivesContent': 'Expandir nuestra red de franquicias a nivel nacional, mantener los más altos estándares de servicio y ser el referente en el sector inmobiliario boliviano.',
    'about.joinTitle': '¿Listo para formar parte de DOMINIO?',
    'about.joinSubtitle': 'Únete a la red inmobiliaria más confiable de Bolivia. Descubre cómo podemos ayudarte a alcanzar tus objetivos inmobiliarios.',
    'about.viewProperties': 'Ver Propiedades',
    'about.requestFranchise': 'Solicitar Franquicia',
    'about.contact': 'Contactar',
    'about.loading': 'Cargando...',

    // Contact page
    'contact.title': 'Contacto',
    'contact.name': 'Nombre',
    'contact.namePlaceholder': 'Tu nombre',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'tu@correo.com',
    'contact.phone': 'Número de Celular',
    'contact.phonePlaceholder': 'Ej: 7XXXXXXXX',
    'contact.whatsapp': 'WhatsApp',
    'contact.whatsappPlaceholder': 'Ej: 7XXXXXXXX',
    'contact.message': 'Mensaje',
    'contact.messagePlaceholder': '¿En qué podemos ayudarte?',
    'contact.send': 'Enviar',
    'contact.sending': 'Enviando...',
    'contact.successMessage': '¡Gracias! Tu mensaje ha sido enviado. Te contactaremos pronto.',
    'contact.errorMessage': 'Hubo un error al enviar tu mensaje. Por favor intenta nuevamente.',

    // Footer
    'footer.description': 'La red de franquicias inmobiliarias más grande de Bolivia.',
    'footer.links': 'Enlaces',
    'footer.copyright': 'Todos los derechos reservados.'
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.properties': 'Properties',
    'nav.agents': 'Our Agents',
    'nav.clients': 'Our Clients',
    'nav.about': 'About Us',
    'nav.contact': 'Contact',
    'nav.login': 'Sign In',
    'nav.register': 'Register',
    'nav.dashboard': 'Dashboard',
    'nav.signOut': 'Sign Out',
    
    // Hero Section
    'hero.title': 'Home for Your Family, Projects for Your Future',
    'hero.subtitle': 'Bolivia\'s largest real estate franchise network. Thousands of verified properties, certified agents and DOMINIO\'s backing.',
    'hero.sellRent': 'Sell or Rent',
    'hero.explore': 'Explore Properties',
    'hero.franchise': 'Join as Franchise',
    
    // Property Types
    'properties.featured': 'Featured Properties',
    'properties.success': 'Recent Successes',
    'properties.house': 'Houses',
    'properties.apartment': 'Apartments',
    'properties.land': 'Land',
    'properties.office': 'Offices',
    'properties.commercial': 'Commercial Space',
    
    // Stats
    'stats.title': 'Numbers That Speak for Themselves',
    'stats.properties': 'Active Properties',
    'stats.franchises': 'Active Franchises',
    'stats.cities': 'Cities',
    'stats.sales': 'Monthly Sales',
    
    // Language Selector
    'language.select': 'Select language',
    'language.spanish': 'Español',
    'language.english': 'English',
    'language.french': 'Français',
    'language.german': 'Deutsch',
    'language.portuguese': 'Português (Brasil)',
    'language.chinese': '繁體中文',

    // Properties page
    'properties.title': 'Find your next home',
    'properties.subtitle': 'Filter by city, budget, rooms and more. All properties are verified by DOMINIO.',
    'properties.filters': 'Filters',
    'properties.transactionType': 'Transaction Type',
    'properties.all': 'All',
    'properties.sale': 'Sale',
    'properties.rent': 'Rent',
    'properties.anticretico': 'Anticretico',
    'properties.department': 'Department',
    'properties.allDepartments': 'All departments',
    'properties.selectDepartment': 'Select department',
    'properties.province': 'Province',
    'properties.allProvinces': 'All provinces',
    'properties.selectProvince': 'Select province',
    'properties.specificZone': 'Specific zone',
    'properties.allZones': 'All zones',
    'properties.minPrice': 'Min price',
    'properties.maxPrice': 'Max price',
    'properties.bedrooms': 'Bedrooms',
    'properties.bathrooms': 'Bathrooms',
    'properties.propertyType': 'Type',
    'properties.select': 'Select',
    'properties.lifestyle': 'AURA search (lifestyle)',
    'properties.lifestylePlaceholder': 'E.g. near parks, quiet area, coworking...',
    'properties.searchNearMe': 'Search near me',
    'properties.amenities': 'Amenities',
    'properties.search': 'Search',
    'properties.clearFilters': 'Clear filters',
    'properties.results': 'Results',
    'properties.propertiesFound': 'properties',
    'properties.loading': 'Loading properties...',
    'properties.noResults': 'No properties found with the selected filters.',
    'properties.tryDifferentFilters': 'Try different filters.',

    // Agents page
    'agents.title': 'Our Agents',
    'agents.subtitle': 'Certified and experienced professionals, ready to help you find the perfect property throughout Bolivia.',
    'agents.searchPlaceholder': 'Search by name or agent code...',
    'agents.minRating': 'Minimum rating',
    'agents.allRatings': 'All ratings',
    'agents.stars': 'stars',
    'agents.showing': 'Showing',
    'agents.of': 'of',
    'agents.agentsText': 'agents',
    'agents.soonTitle': 'Coming Soon',
    'agents.soonSubtitle': 'We are preparing our professional agents\' profiles.',
    'agents.realEstateAgent': 'Real Estate Agent',
    'agents.code': 'Code',
    'agents.availableInBolivia': 'Available in Bolivia',
    'agents.viewFullProfile': 'View Full Profile',
    'agents.loadMore': 'Load more agents',
    'agents.needHelp': 'Need personalized help?',
    'agents.helpText': 'Our agents are ready to advise you in finding your ideal property. Contact any of them directly.',
    'agents.contactNow': 'Contact Now',
    'agents.loading': 'Loading agents...',

    // About page
    'about.title': 'About DOMINIO',
    'about.defaultContent': 'DOMINIO Real Estate was born from the vision of creating the largest and most reliable real estate franchise network in Bolivia. Our mission is to connect people with homes, providing transparency, trust and excellence in every transaction.',
    'about.pillarsTitle': 'Our Pillars',
    'about.pillarsSubtitle': 'The values and principles that guide our daily work and drive us towards excellence.',
    'about.mission': 'Our Mission',
    'about.missionContent': 'To be the reliable bridge between people and their real estate dreams, providing excellent services and transparency in every transaction.',
    'about.vision': 'Our Vision',
    'about.visionContent': 'To become the leading real estate network in Bolivia, recognized for our integrity, innovation and commitment to our clients.',
    'about.values': 'Our Values',
    'about.valuesContent': 'Transparency, Trust, Excellence, Innovation and Commitment to our clients and communities.',
    'about.objectives': 'Our Objectives',
    'about.objectivesContent': 'Expand our franchise network nationwide, maintain the highest service standards and be the benchmark in the Bolivian real estate sector.',
    'about.joinTitle': 'Ready to be part of DOMINIO?',
    'about.joinSubtitle': 'Join Bolivia\'s most trusted real estate network. Discover how we can help you achieve your real estate goals.',
    'about.viewProperties': 'View Properties',
    'about.requestFranchise': 'Request Franchise',
    'about.contact': 'Contact',
    'about.loading': 'Loading...',

    // Contact page
    'contact.title': 'Contact',
    'contact.name': 'Name',
    'contact.namePlaceholder': 'Your name',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'your@email.com',
    'contact.phone': 'Phone Number',
    'contact.phonePlaceholder': 'E.g: 7XXXXXXXX',
    'contact.whatsapp': 'WhatsApp',
    'contact.whatsappPlaceholder': 'E.g: 7XXXXXXXX',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'How can we help you?',
    'contact.send': 'Send',
    'contact.sending': 'Sending...',
    'contact.successMessage': 'Thank you! Your message has been sent. We will contact you soon.',
    'contact.errorMessage': 'There was an error sending your message. Please try again.',

    // Footer
    'footer.description': 'The largest real estate franchise network in Bolivia.',
    'footer.links': 'Links',
    'footer.copyright': 'All rights reserved.'
  },
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.properties': 'Propriétés',
    'nav.agents': 'Nos Agents',
    'nav.clients': 'Nos Clients',
    'nav.about': 'À Propos',
    'nav.contact': 'Contact',
    'nav.login': 'Se Connecter',
    'nav.register': 'S\'inscrire',
    'nav.dashboard': 'Tableau de Bord',
    'nav.signOut': 'Se Déconnecter',
    
    // Hero Section
    'hero.title': 'Maison pour Votre Famille, Projets pour Votre Avenir',
    'hero.subtitle': 'Le plus grand réseau de franchises immobilières de Bolivie. Des milliers de propriétés vérifiées, des agents certifiés et le soutien de DOMINIO.',
    'hero.sellRent': 'Vendre ou Louer',
    'hero.explore': 'Explorer les Propriétés',
    'hero.franchise': 'Rejoindre comme Franchise',
    
    // Property Types
    'properties.featured': 'Propriétés en Vedette',
    'properties.success': 'Succès Récents',
    'properties.house': 'Maisons',
    'properties.apartment': 'Appartements',
    'properties.land': 'Terrains',
    'properties.office': 'Bureaux',
    'properties.commercial': 'Local commercial',
    
    // Stats
    'stats.title': 'Des Chiffres Qui Parlent d\'Eux-Mêmes',
    'stats.properties': 'Propriétés Actives',
    'stats.franchises': 'Franchises Actives',
    'stats.cities': 'Villes',
    'stats.sales': 'Ventes Mensuelles',
    
    // Language Selector
    'language.select': 'Sélectionner la langue',
    'language.spanish': 'Español',
    'language.english': 'English',
    'language.french': 'Français',
    'language.german': 'Deutsch',
    'language.portuguese': 'Português (Brasil)',
    'language.chinese': '繁體中文',

    // Properties page
    'properties.title': 'Trouvez votre prochain foyer',
    'properties.subtitle': 'Filtrez par ville, budget, chambres et plus. Toutes les propriétés sont vérifiées par DOMINIO.',
    'properties.filters': 'Filtres',
    'properties.transactionType': 'Type de Transaction',
    'properties.all': 'Toutes',
    'properties.sale': 'Vente',
    'properties.rent': 'Location',
    'properties.anticretico': 'Anticrético',
    'properties.department': 'Département',
    'properties.allDepartments': 'Tous les départements',
    'properties.selectDepartment': 'Sélectionnez un département',
    'properties.province': 'Province',
    'properties.allProvinces': 'Toutes les provinces',
    'properties.selectProvince': 'Sélectionnez une province',
    'properties.specificZone': 'Zone spécifique',
    'properties.allZones': 'Toutes les zones',
    'properties.minPrice': 'Prix min.',
    'properties.maxPrice': 'Prix max.',
    'properties.bedrooms': 'Chambres',
    'properties.bathrooms': 'Salles de bain',
    'properties.propertyType': 'Type',
    'properties.select': 'Sélectionner',
    'properties.lifestyle': 'Recherche AURA (style de vie)',
    'properties.lifestylePlaceholder': 'Ex. près des parcs, zone tranquille, coworking...',
    'properties.searchNearMe': 'Rechercher près de moi',
    'properties.amenities': 'Commodités',
    'properties.search': 'Rechercher',
    'properties.clearFilters': 'Effacer les filtres',
    'properties.results': 'Résultats',
    'properties.propertiesFound': 'propriétés',
    'properties.loading': 'Chargement des propriétés...',
    'properties.noResults': 'Aucune propriété trouvée avec les filtres sélectionnés.',
    'properties.tryDifferentFilters': 'Essayez avec des filtres différents.',

    // Agents page
    'agents.title': 'Nos Agents',
    'agents.subtitle': 'Professionnels certifiés et expérimentés, prêts à vous aider à trouver la propriété parfaite en Bolivie.',
    'agents.searchPlaceholder': 'Rechercher par nom ou code d\'agent...',
    'agents.minRating': 'Note minimale',
    'agents.allRatings': 'Toutes les notes',
    'agents.stars': 'étoiles',
    'agents.showing': 'Affichage',
    'agents.of': 'de',
    'agents.agentsText': 'agents',
    'agents.soonTitle': 'Prochainement',
    'agents.soonSubtitle': 'Nous préparons les profils de nos agents professionnels.',
    'agents.realEstateAgent': 'Agent Immobilier',
    'agents.code': 'Code',
    'agents.availableInBolivia': 'Disponible en Bolivie',
    'agents.viewFullProfile': 'Voir le Profil Complet',
    'agents.loadMore': 'Charger plus d\'agents',
    'agents.needHelp': 'Besoin d\'aide personnalisée?',
    'agents.helpText': 'Nos agents sont prêts à vous conseiller dans la recherche de votre propriété idéale. Contactez-les directement.',
    'agents.contactNow': 'Contacter Maintenant',
    'agents.loading': 'Chargement des agents...',

    // About page
    'about.title': 'À Propos de DOMINIO',
    'about.defaultContent': 'DOMINIO Immobilier est né de la vision de créer le plus grand et le plus fiable réseau de franchises immobilières de Bolivie. Notre mission est de connecter les personnes aux maisons, en fournissant transparence, confiance et excellence dans chaque transaction.',
    'about.pillarsTitle': 'Nos Piliers',
    'about.pillarsSubtitle': 'Les valeurs et principes qui guident notre travail quotidien et nous poussent vers l\'excellence.',
    'about.mission': 'Notre Mission',
    'about.missionContent': 'Être le pont fiable entre les personnes et leurs rêves immobiliers, en fournissant des services d\'excellence et de transparence dans chaque transaction.',
    'about.vision': 'Notre Vision',
    'about.visionContent': 'Devenir le réseau immobilier leader en Bolivie, reconnu pour notre intégrité, innovation et engagement envers nos clients.',
    'about.values': 'Nos Valeurs',
    'about.valuesContent': 'Transparence, Confiance, Excellence, Innovation et Engagement envers nos clients et communautés.',
    'about.objectives': 'Nos Objectifs',
    'about.objectivesContent': 'Étendre notre réseau de franchises à l\'échelle nationale, maintenir les plus hauts standards de service et être la référence dans le secteur immobilier bolivien.',
    'about.joinTitle': 'Prêt à faire partie de DOMINIO?',
    'about.joinSubtitle': 'Rejoignez le réseau immobilier le plus fiable de Bolivie. Découvrez comment nous pouvons vous aider à atteindre vos objectifs immobiliers.',
    'about.viewProperties': 'Voir les Propriétés',
    'about.requestFranchise': 'Demander une Franchise',
    'about.contact': 'Contact',
    'about.loading': 'Chargement...',

    // Contact page
    'contact.title': 'Contact',
    'contact.name': 'Nom',
    'contact.namePlaceholder': 'Votre nom',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'votre@email.com',
    'contact.phone': 'Numéro de Téléphone',
    'contact.phonePlaceholder': 'Ex: 7XXXXXXXX',
    'contact.whatsapp': 'WhatsApp',
    'contact.whatsappPlaceholder': 'Ex: 7XXXXXXXX',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Comment pouvons-nous vous aider?',
    'contact.send': 'Envoyer',
    'contact.sending': 'Envoi en cours...',
    'contact.successMessage': 'Merci! Votre message a été envoyé. Nous vous contacterons bientôt.',
    'contact.errorMessage': 'Il y a eu une erreur lors de l\'envoi de votre message. Veuillez réessayer.',

    // Footer
    'footer.description': 'Le plus grand réseau de franchises immobilières de Bolivie.',
    'footer.links': 'Liens',
    'footer.copyright': 'Tous droits réservés.'
  },
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.properties': 'Immobilien',
    'nav.agents': 'Unsere Makler',
    'nav.clients': 'Unsere Kunden',
    'nav.about': 'Über Uns',
    'nav.contact': 'Kontakt',
    'nav.login': 'Anmelden',
    'nav.register': 'Registrieren',
    'nav.dashboard': 'Dashboard',
    'nav.signOut': 'Abmelden',
    
    // Hero Section
    'hero.title': 'Zuhause für Ihre Familie, Projekte für Ihre Zukunft',
    'hero.subtitle': 'Boliviens größtes Immobilien-Franchise-Netzwerk. Tausende verifizierte Immobilien, zertifizierte Makler und DOMINIOs Unterstützung.',
    'hero.sellRent': 'Verkaufen oder Vermieten',
    'hero.explore': 'Immobilien Erkunden',
    'hero.franchise': 'Als Franchise Beitreten',
    
    // Property Types
    'properties.featured': 'Ausgewählte Immobilien',
    'properties.success': 'Jüngste Erfolge',
    'properties.house': 'Häuser',
    'properties.apartment': 'Wohnungen',
    'properties.land': 'Grundstücke',
    'properties.office': 'Büros',
    'properties.commercial': 'Gewerberaum',
    
    // Stats
    'stats.title': 'Zahlen, die für sich Sprechen',
    'stats.properties': 'Aktive Immobilien',
    'stats.franchises': 'Aktive Franchises',
    'stats.cities': 'Städte',
    'stats.sales': 'Monatliche Verkäufe',
    
    // Language Selector
    'language.select': 'Sprache auswählen',
    'language.spanish': 'Español',
    'language.english': 'English',
    'language.french': 'Français',
    'language.german': 'Deutsch',
    'language.portuguese': 'Português (Brasil)',
    'language.chinese': '繁體中文',

    // Properties page
    'properties.title': 'Finden Sie Ihr nächstes Zuhause',
    'properties.subtitle': 'Filtern Sie nach Stadt, Budget, Zimmern und mehr. Alle Immobilien sind von DOMINIO verifiziert.',
    'properties.filters': 'Filter',
    'properties.transactionType': 'Transaktionstyp',
    'properties.all': 'Alle',
    'properties.sale': 'Verkauf',
    'properties.rent': 'Miete',
    'properties.anticretico': 'Anticrético',
    'properties.department': 'Departement',
    'properties.allDepartments': 'Alle Departemente',
    'properties.selectDepartment': 'Departement auswählen',
    'properties.province': 'Provinz',
    'properties.allProvinces': 'Alle Provinzen',
    'properties.selectProvince': 'Provinz auswählen',
    'properties.specificZone': 'Spezifische Zone',
    'properties.allZones': 'Alle Zonen',
    'properties.minPrice': 'Min. Preis',
    'properties.maxPrice': 'Max. Preis',
    'properties.bedrooms': 'Schlafzimmer',
    'properties.bathrooms': 'Badezimmer',
    'properties.propertyType': 'Typ',
    'properties.select': 'Auswählen',
    'properties.lifestyle': 'AURA-Suche (Lebensstil)',
    'properties.lifestylePlaceholder': 'Z.B. nahe Parks, ruhige Gegend, Coworking...',
    'properties.searchNearMe': 'In meiner Nähe suchen',
    'properties.amenities': 'Annehmlichkeiten',
    'properties.search': 'Suchen',
    'properties.clearFilters': 'Filter löschen',
    'properties.results': 'Ergebnisse',
    'properties.propertiesFound': 'Immobilien',
    'properties.loading': 'Lade Immobilien...',
    'properties.noResults': 'Keine Immobilien mit den ausgewählten Filtern gefunden.',
    'properties.tryDifferentFilters': 'Versuchen Sie es mit anderen Filtern.',

    // Agents page
    'agents.title': 'Unsere Makler',
    'agents.subtitle': 'Zertifizierte und erfahrene Profis, bereit Ihnen zu helfen, die perfekte Immobilie in ganz Bolivien zu finden.',
    'agents.searchPlaceholder': 'Nach Name oder Makler-Code suchen...',
    'agents.minRating': 'Mindestbewertung',
    'agents.allRatings': 'Alle Bewertungen',
    'agents.stars': 'Sterne',
    'agents.showing': 'Zeige',
    'agents.of': 'von',
    'agents.agentsText': 'Makler',
    'agents.soonTitle': 'Demnächst',
    'agents.soonSubtitle': 'Wir bereiten die Profile unserer professionellen Makler vor.',
    'agents.realEstateAgent': 'Immobilienmakler',
    'agents.code': 'Code',
    'agents.availableInBolivia': 'Verfügbar in Bolivien',
    'agents.viewFullProfile': 'Vollständiges Profil ansehen',
    'agents.loadMore': 'Weitere Makler laden',
    'agents.needHelp': 'Brauchen Sie personalisierte Hilfe?',
    'agents.helpText': 'Unsere Makler sind bereit, Sie bei der Suche nach Ihrer idealen Immobilie zu beraten. Kontaktieren Sie sie direkt.',
    'agents.contactNow': 'Jetzt Kontaktieren',
    'agents.loading': 'Lade Makler...',

    // About page
    'about.title': 'Über DOMINIO',
    'about.defaultContent': 'DOMINIO Immobilien entstand aus der Vision, das größte und zuverlässigste Immobilien-Franchise-Netzwerk in Bolivien zu schaffen. Unsere Mission ist es, Menschen mit Häusern zu verbinden und Transparenz, Vertrauen und Exzellenz in jeder Transaktion zu bieten.',
    'about.pillarsTitle': 'Unsere Säulen',
    'about.pillarsSubtitle': 'Die Werte und Prinzipien, die unsere tägliche Arbeit leiten und uns zur Exzellenz antreiben.',
    'about.mission': 'Unsere Mission',
    'about.missionContent': 'Die zuverlässige Brücke zwischen Menschen und ihren Immobilienträumen zu sein und exzellente Dienstleistungen mit Transparenz in jeder Transaktion zu bieten.',
    'about.vision': 'Unsere Vision',
    'about.visionContent': 'Das führende Immobilien-Netzwerk in Bolivien zu werden, anerkannt für unsere Integrität, Innovation und Engagement für unsere Kunden.',
    'about.values': 'Unsere Werte',
    'about.valuesContent': 'Transparenz, Vertrauen, Exzellenz, Innovation und Engagement für unsere Kunden und Gemeinschaften.',
    'about.objectives': 'Unsere Ziele',
    'about.objectivesContent': 'Unser Franchise-Netzwerk landesweit auszubauen, die höchsten Service-Standards zu halten und der Maßstab im bolivianischen Immobiliensektor zu sein.',
    'about.joinTitle': 'Bereit, Teil von DOMINIO zu werden?',
    'about.joinSubtitle': 'Treten Sie dem vertrauenswürdigsten Immobilien-Netzwerk Boliviens bei. Entdecken Sie, wie wir Ihnen helfen können, Ihre Immobilienziele zu erreichen.',
    'about.viewProperties': 'Immobilien ansehen',
    'about.requestFranchise': 'Franchise anfragen',
    'about.contact': 'Kontakt',
    'about.loading': 'Lädt...',

    // Contact page
    'contact.title': 'Kontakt',
    'contact.name': 'Name',
    'contact.namePlaceholder': 'Ihr Name',
    'contact.email': 'E-Mail',
    'contact.emailPlaceholder': 'ihre@email.com',
    'contact.phone': 'Telefonnummer',
    'contact.phonePlaceholder': 'Z.B: 7XXXXXXXX',
    'contact.whatsapp': 'WhatsApp',
    'contact.whatsappPlaceholder': 'Z.B: 7XXXXXXXX',
    'contact.message': 'Nachricht',
    'contact.messagePlaceholder': 'Wie können wir Ihnen helfen?',
    'contact.send': 'Senden',
    'contact.sending': 'Wird gesendet...',
    'contact.successMessage': 'Danke! Ihre Nachricht wurde gesendet. Wir werden Sie bald kontaktieren.',
    'contact.errorMessage': 'Beim Senden Ihrer Nachricht ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut.',

    // Footer
    'footer.description': 'Das größte Immobilien-Franchise-Netzwerk in Bolivien.',
    'footer.links': 'Links',
    'footer.copyright': 'Alle Rechte vorbehalten.'
  },
  pt: {
    // Navigation
    'nav.home': 'Início',
    'nav.properties': 'Propriedades',
    'nav.agents': 'Nossos Corretores',
    'nav.clients': 'Nossos Clientes',
    'nav.about': 'Sobre Nós',
    'nav.contact': 'Contato',
    'nav.login': 'Entrar',
    'nav.register': 'Registrar-se',
    'nav.dashboard': 'Painel',
    'nav.signOut': 'Sair',
    
    // Hero Section
    'hero.title': 'Lar para Sua Família, Projetos para Seu Futuro',
    'hero.subtitle': 'A maior rede de franquias imobiliárias da Bolívia. Milhares de propriedades verificadas, corretores certificados e o respaldo da DOMINIO.',
    'hero.sellRent': 'Vender ou Alugar',
    'hero.explore': 'Explorar Propriedades',
    'hero.franchise': 'Junte-se como Franquia',
    
    // Property Types
    'properties.featured': 'Propriedades em Destaque',
    'properties.success': 'Sucessos Recentes',
    'properties.house': 'Casas',
    'properties.apartment': 'Apartamentos',
    'properties.land': 'Terrenos',
    'properties.office': 'Escritórios',
    'properties.commercial': 'Espaço comercial',
    
    // Stats
    'stats.title': 'Números que Falam por Si',
    'stats.properties': 'Propriedades Ativas',
    'stats.franchises': 'Franquias Ativas',
    'stats.cities': 'Cidades',
    'stats.sales': 'Vendas Mensais',
    
    // Language Selector
    'language.select': 'Selecionar idioma',
    'language.spanish': 'Español',
    'language.english': 'English',
    'language.french': 'Français',
    'language.german': 'Deutsch',
    'language.portuguese': 'Português (Brasil)',
    'language.chinese': '繁體中文',

    // Properties page
    'properties.title': 'Encontre sua próxima casa',
    'properties.subtitle': 'Filtre por cidade, orçamento, quartos e mais. Todas as propriedades são verificadas pela DOMINIO.',
    'properties.filters': 'Filtros',
    'properties.transactionType': 'Tipo de Transação',
    'properties.all': 'Todas',
    'properties.sale': 'Venda',
    'properties.rent': 'Aluguel',
    'properties.anticretico': 'Anticrético',
    'properties.department': 'Departamento',
    'properties.allDepartments': 'Todos os departamentos',
    'properties.selectDepartment': 'Selecionar departamento',
    'properties.province': 'Província',
    'properties.allProvinces': 'Todas as províncias',
    'properties.selectProvince': 'Selecionar província',
    'properties.specificZone': 'Zona específica',
    'properties.allZones': 'Todas as zonas',
    'properties.minPrice': 'Preço mín.',
    'properties.maxPrice': 'Preço máx.',
    'properties.bedrooms': 'Quartos',
    'properties.bathrooms': 'Banheiros',
    'properties.propertyType': 'Tipo',
    'properties.select': 'Selecionar',
    'properties.lifestyle': 'Busca AURA (estilo de vida)',
    'properties.lifestylePlaceholder': 'Ex. perto de parques, área tranquila, coworking...',
    'properties.searchNearMe': 'Buscar perto de mim',
    'properties.amenities': 'Comodidades',
    'properties.search': 'Buscar',
    'properties.clearFilters': 'Limpar filtros',
    'properties.results': 'Resultados',
    'properties.propertiesFound': 'propriedades',
    'properties.loading': 'Carregando propriedades...',
    'properties.noResults': 'Nenhuma propriedade encontrada com os filtros selecionados.',
    'properties.tryDifferentFilters': 'Tente com filtros diferentes.',

    // Agents page
    'agents.title': 'Nossos Corretores',
    'agents.subtitle': 'Profissionais certificados e experientes, prontos para ajudar você a encontrar a propriedade perfeita em toda a Bolívia.',
    'agents.searchPlaceholder': 'Buscar por nome ou código do corretor...',
    'agents.minRating': 'Classificação mínima',
    'agents.allRatings': 'Todas as classificações',
    'agents.stars': 'estrelas',
    'agents.showing': 'Mostrando',
    'agents.of': 'de',
    'agents.agentsText': 'corretores',
    'agents.soonTitle': 'Em Breve',
    'agents.soonSubtitle': 'Estamos preparando os perfis de nossos corretores profissionais.',
    'agents.realEstateAgent': 'Corretor de Imóveis',
    'agents.code': 'Código',
    'agents.availableInBolivia': 'Disponível na Bolívia',
    'agents.viewFullProfile': 'Ver Perfil Completo',
    'agents.loadMore': 'Carregar mais corretores',
    'agents.needHelp': 'Precisa de ajuda personalizada?',
    'agents.helpText': 'Nossos corretores estão prontos para assessorá-lo na busca por sua propriedade ideal. Entre em contato diretamente com qualquer um deles.',
    'agents.contactNow': 'Contatar Agora',
    'agents.loading': 'Carregando corretores...',

    // About page
    'about.title': 'Sobre DOMINIO',
    'about.defaultContent': 'DOMINIO Imobiliária nasceu da visão de criar a maior e mais confiável rede de franquias imobiliárias da Bolívia. Nossa missão é conectar pessoas a casas, proporcionando transparência, confiança e excelência em cada transação.',
    'about.pillarsTitle': 'Nossos Pilares',
    'about.pillarsSubtitle': 'Os valores e princípios que guiam nosso trabalho diário e nos impulsionam à excelência.',
    'about.mission': 'Nossa Missão',
    'about.missionContent': 'Ser a ponte confiável entre as pessoas e seus sonhos imobiliários, proporcionando serviços de excelência e transparência em cada transação.',
    'about.vision': 'Nossa Visão',
    'about.visionContent': 'Tornar-se a rede imobiliária líder na Bolívia, reconhecida por nossa integridade, inovação e compromisso com nossos clientes.',
    'about.values': 'Nossos Valores',
    'about.valuesContent': 'Transparência, Confiança, Excelência, Inovação e Compromisso com nossos clientes e comunidades.',
    'about.objectives': 'Nossos Objetivos',
    'about.objectivesContent': 'Expandir nossa rede de franquias nacionalmente, manter os mais altos padrões de serviço e ser a referência no setor imobiliário boliviano.',
    'about.joinTitle': 'Pronto para fazer parte da DOMINIO?',
    'about.joinSubtitle': 'Junte-se à rede imobiliária mais confiável da Bolívia. Descubra como podemos ajudar você a alcançar seus objetivos imobiliários.',
    'about.viewProperties': 'Ver Propriedades',
    'about.requestFranchise': 'Solicitar Franquia',
    'about.contact': 'Contato',
    'about.loading': 'Carregando...',

    // Contact page
    'contact.title': 'Contato',
    'contact.name': 'Nome',
    'contact.namePlaceholder': 'Seu nome',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'seu@email.com',
    'contact.phone': 'Número de Celular',
    'contact.phonePlaceholder': 'Ex: 7XXXXXXXX',
    'contact.whatsapp': 'WhatsApp',
    'contact.whatsappPlaceholder': 'Ex: 7XXXXXXXX',
    'contact.message': 'Mensagem',
    'contact.messagePlaceholder': 'Como podemos ajudá-lo?',
    'contact.send': 'Enviar',
    'contact.sending': 'Enviando...',
    'contact.successMessage': 'Obrigado! Sua mensagem foi enviada. Entraremos em contato em breve.',
    'contact.errorMessage': 'Houve um erro ao enviar sua mensagem. Tente novamente.',

    // Footer
    'footer.description': 'A maior rede de franquias imobiliárias da Bolívia.',
    'footer.links': 'Links',
    'footer.copyright': 'Todos os direitos reservados.'
  },
  zh: {
    // Navigation
    'nav.home': '首頁',
    'nav.properties': '物業',
    'nav.agents': '我們的代理人',
    'nav.clients': '我們的客戶',
    'nav.about': '關於我們',
    'nav.contact': '聯繫我們',
    'nav.login': '登入',
    'nav.register': '註冊',
    'nav.dashboard': '儀表板',
    'nav.signOut': '登出',
    
    // Hero Section
    'hero.title': '為您的家庭築家，為您的未來築夢',
    'hero.subtitle': '玻利維亞最大的房地產加盟網絡。數千套經過驗證的物業，認證代理人和DOMINIO的支持。',
    'hero.sellRent': '出售或出租',
    'hero.explore': '探索物業',
    'hero.franchise': '加入加盟',
    
    // Property Types
    'properties.featured': '精選物業',
    'properties.success': '最近成功案例',
    'properties.house': '房屋',
    'properties.apartment': '公寓',
    'properties.land': '土地',
    'properties.office': '辦公室',
    'properties.commercial': '商業空間',
    
    // Stats
    'stats.title': '用數字說話',
    'stats.properties': '活躍物業',
    'stats.franchises': '活躍加盟店',
    'stats.cities': '城市',
    'stats.sales': '月銷量',
    
    // Language Selector
    'language.select': '選擇語言',
    'language.spanish': 'Español',
    'language.english': 'English',
    'language.french': 'Français',
    'language.german': 'Deutsch',
    'language.portuguese': 'Português (Brasil)',
    'language.chinese': '繁體中文',

    // Properties page
    'properties.title': '尋找您的下一個家',
    'properties.subtitle': '按城市、預算、房間數量等篩選。所有物業均由DOMINIO驗證。',
    'properties.filters': '篩選器',
    'properties.transactionType': '交易類型',
    'properties.all': '全部',
    'properties.sale': '出售',
    'properties.rent': '租賃',
    'properties.anticretico': '預付租金',
    'properties.department': '省份',
    'properties.allDepartments': '所有省份',
    'properties.selectDepartment': '選擇省份',
    'properties.province': '州',
    'properties.allProvinces': '所有州',
    'properties.selectProvince': '選擇州',
    'properties.specificZone': '特定區域',
    'properties.allZones': '所有區域',
    'properties.minPrice': '最低價格',
    'properties.maxPrice': '最高價格',
    'properties.bedrooms': '臥室',
    'properties.bathrooms': '浴室',
    'properties.propertyType': '類型',
    'properties.select': '選擇',
    'properties.lifestyle': 'AURA搜索（生活方式）',
    'properties.lifestylePlaceholder': '例如：靠近公園、安靜區域、共享辦公...',
    'properties.searchNearMe': '搜索我附近',
    'properties.amenities': '便利設施',
    'properties.search': '搜索',
    'properties.clearFilters': '清除篩選器',
    'properties.results': '結果',
    'properties.propertiesFound': '物業',
    'properties.loading': '載入物業中...',
    'properties.noResults': '未找到符合所選篩選條件的物業。',
    'properties.tryDifferentFilters': '嘗試不同的篩選條件。',

    // Agents page
    'agents.title': '我們的代理人',
    'agents.subtitle': '經過認證和經驗豐富的專業人士，準備幫助您在整個玻利維亞找到完美的物業。',
    'agents.searchPlaceholder': '按姓名或代理人代碼搜索...',
    'agents.minRating': '最低評分',
    'agents.allRatings': '所有評分',
    'agents.stars': '星',
    'agents.showing': '顯示',
    'agents.of': '之',
    'agents.agentsText': '代理人',
    'agents.soonTitle': '即將推出',
    'agents.soonSubtitle': '我們正在準備專業代理人的個人檔案。',
    'agents.realEstateAgent': '房地產代理',
    'agents.code': '代碼',
    'agents.availableInBolivia': '在玻利維亞提供服務',
    'agents.viewFullProfile': '查看完整檔案',
    'agents.loadMore': '載入更多代理人',
    'agents.needHelp': '需要個性化幫助？',
    'agents.helpText': '我們的代理人準備為您尋找理想物業提供建議。直接聯繫他們任何一位。',
    'agents.contactNow': '立即聯繫',
    'agents.loading': '載入代理人中...',

    // About page
    'about.title': '關於DOMINIO',
    'about.defaultContent': 'DOMINIO房地產誕生於創建玻利維亞最大最可靠房地產加盟網絡的願景。我們的使命是將人與家連接，在每筆交易中提供透明度、信任和卓越。',
    'about.pillarsTitle': '我們的支柱',
    'about.pillarsSubtitle': '指導我們日常工作並推動我們追求卓越的價值觀和原則。',
    'about.mission': '我們的使命',
    'about.missionContent': '成為人們與房地產夢想之間可靠的橋樑，在每筆交易中提供卓越的服務和透明度。',
    'about.vision': '我們的願景',
    'about.visionContent': '成為玻利維亞領先的房地產網絡，以我們的誠信、創新和對客戶的承諾而聞名。',
    'about.values': '我們的價值觀',
    'about.valuesContent': '透明度、信任、卓越、創新以及對客戶和社區的承諾。',
    'about.objectives': '我們的目標',
    'about.objectivesContent': '在全國範圍內擴展我們的加盟網絡，保持最高的服務標準，成為玻利維亞房地產行業的基準。',
    'about.joinTitle': '準備好成為DOMINIO的一部分？',
    'about.joinSubtitle': '加入玻利維亞最值得信賴的房地產網絡。了解我們如何幫助您實現房地產目標。',
    'about.viewProperties': '查看物業',
    'about.requestFranchise': '申請加盟',
    'about.contact': '聯繫',
    'about.loading': '載入中...',

    // Contact page
    'contact.title': '聯繫我們',
    'contact.name': '姓名',
    'contact.namePlaceholder': '您的姓名',
    'contact.email': '電子郵件',
    'contact.emailPlaceholder': '您的@email.com',
    'contact.phone': '電話號碼',
    'contact.phonePlaceholder': '例如：7XXXXXXXX',
    'contact.whatsapp': 'WhatsApp',
    'contact.whatsappPlaceholder': '例如：7XXXXXXXX',
    'contact.message': '訊息',
    'contact.messagePlaceholder': '我們如何幫助您？',
    'contact.send': '發送',
    'contact.sending': '發送中...',
    'contact.successMessage': '謝謝！您的訊息已發送。我們將很快聯繫您。',
    'contact.errorMessage': '發送訊息時出現錯誤。請再試一次。',

    // Footer
    'footer.description': '玻利維亞最大的房地產加盟網絡。',
    'footer.links': '連結',
    'footer.copyright': '版權所有。'
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('es');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('dominio-language') as Language;
    if (savedLanguage && Object.keys(translations).includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  const changeLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('dominio-language', lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}